-- Create beer_details table with foreign key to beers
CREATE TABLE beer_details (
  id TEXT PRIMARY KEY,
  beer_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  malt JSON,
  hops JSON,
  mash JSON,
  yeast TEXT,
  og REAL,
  fg REAL,
  alc REAL,
  mash_water_liters REAL,
  sparge_water_liters REAL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (beer_id) REFERENCES beers(id)
);

-- Insert beer details (currently mostly placeholder with limited data from files)
INSERT INTO beer_details (id, beer_id, title, description, yeast, og, fg, alc, mash_water_liters, sparge_water_liters) VALUES
('32-watermeloen-ipa-detail', '32-watermeloen-ipa', '#32 Watermeloen IPA', 'De Tripel Karmeliet, wie kent ''m niet. Het driegranenbier bij uitstek. Naast gerst wordt er ook tarwe en haver gebruikt.', 'T-58', 1.085, 1.024, 8.4, 8.0, 9.0),
('33-zwaar-blond-detail', '33-zwaar-blond', '#33 Zwaar blond', 'De Tripel Karmeliet, wie kent ''m niet. Het driegranenbier bij uitstek. Naast gerst wordt er ook tarwe en haver gebruikt.', NULL, NULL, NULL, NULL, NULL, NULL),
('37-ruby-mild-detail', '37-ruby-mild', '#37 Ruby Mild', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('38-honey-swarm-detail', '38-honey-swarm', '#38 Honey Swarm', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('39-kersen-wit-detail', '39-kersen-wit', '#39 Kersen wit', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('40-stout-detail', '40-stout', '#40 Stout', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('41-neipa-detail', '41-neipa', '#41 NEIPA', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('42-tarwebier-detail', '42-tarwebier', '#42 Tarwebier', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('43-honing-tripel-t-58-detail', '43-honing-tripel-t-58', '#43 Honing tripel T-58', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('43-honing-tripel-s-33-detail', '43-honing-tripel-s-33', '#43 Honing tripel S-33', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('44-dubbel-detail', '44-dubbel', '#44 Dubbel', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('45-restjes-ris-detail', '45-restjes-ris', '#45 Restjes RIS', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('45-restjes-ris-barrel-aged-detail', '45-restjes-ris-barrel-aged', '#45 Restjes RIS BA', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('15-russian-imperial-stout-detail', '15-russian-imperial-stout', 'Nummer 15', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('16-pineapple-ipa-detail', '16-pineapple-ipa', 'Pineapple IPA', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('17-mango-ipa-detail', '17-mango-ipa', 'Mango IPA', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('18-rochefort-10-detail', '18-rochefort-10', 'Rochefort', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('19-kiwi-ipa-detail', '19-kiwi-ipa', 'Kiwi IPA', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('20-tripel-biab-detail', '20-tripel-biab', 'Nummer 20', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('21-dubbel-stout-biab-detail', '21-dubbel-stout-biab', 'Nummer 21', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('22-american-wheat-beer-detail', '22-american-wheat-beer', 'Nummer 22', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('23-london-bitter-detail', '23-london-bitter', 'Nummer 23', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('24-kerstbier-detail', '24-kerstbier', 'Nummer 24', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('25-saison-detail', '25-saison', 'Nummer 25', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('26-coffee-chocolate-milky-stout-detail', '26-coffee-chocolate-milky-stout', 'Nummer 26', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('27-blond-detail', '27-blond', 'Nummer 27', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('xxviii-tripel-detail', 'xxviii-tripel', 'Nummer 28', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('11101-blond-detail', '11101-blond', 'Nummer 29', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('30-drie-granen-tripel-detail', '30-drie-granen-tripel', 'Drie granen tripel', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('31-ris-detail', '31-ris', 'Russian Imperial Stout', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('34-tarwebier-us-05-detail', '34-tarwebier-us-05', 'Tarwebier US-05', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('35-tarwebier-wb-06-detail', '35-tarwebier-wb-06', 'Tarwebier WB-06', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('36-blonde-detail', '36-blonde', 'Blonde IPA', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
