site_name: Brouwerij Robier
site_url: https://www.robier.nl/
site_description: Bieren van Rogier
site_author: Rogier

repo_url: https://github.com/wensink/robier
edit_uri: blob/main/docs/

theme:
    name: material
    locale: en
    highlightjs: true
    hljs_languages:
        - yaml
        - python
    features:
        - navigation.footer

nav:
    - Proost: index.md
    - Bieren: bieren.md
    - About:
        - Brouw notities: about/brouw-notes.md
        - Contact: about/contact.md

extra:
    social:
        - icon: simple/instagram
          link: https://www.instagram.com/brouwerij_robier/
        - icon: simple/untappd
          link: https://untappd.com/b/brouwerij-robier

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - admonition
    - codehilite
    - smarty
    - meta
    - toc:
          permalink: True
    - attr_list

copyright: Copyright &copy; 2023
